Update default parameters

diff --git a/HG-CoLoR b/HG-CoLoR
--- a/HG-CoLoR
+++ b/HG-CoLoR
@@ -19,15 +19,15 @@ function print_help {
 	echo ""
 	echo "	Options:"
 	echo "	--maxorder:	Maximum order of the variable-order de Buijn graph (default: 100)."
-	echo "	--solid:	Minimum number of occurrences to consider a k-mer as solid, after short reads correction (default: 2)."
-	echo "			This parameter should be raised accordingly to the short reads coverage and accuracy."
-	echo "			Its default value is adapted for a 50x coverage of short reads with a 1% error rate."
+	echo "	--solid:	Minimum number of occurrences to consider a k-mer as solid, after short reads correction (default: 1)."
+	echo "			This parameter should be carefully raised accordingly to the short reads coverage and accuracy."
 	echo "	--seedsoverlap:	Minimum overlap length to allow the merging of two overlapping seeds (default: k-1)."
 	echo "	--minorder:	Minimum order of the variable-order de Bruijn graph (default: maxorder/2)."
 	echo "	--branches:	Maximum number of branches exploration (default: 1,500)."
 	echo "			Raising this parameter will result in less fragmented corrected long reads."
 	echo "			However, it will also increase the runtime, and may create chimeric linkings between the seeds."
 	echo "	--seedskips:	Maximum number of seed skips (default: 5)."
+	echo "	--mismatches:	Allowed mismatches when attempting to link two seeds together (default: 3)"
 	echo "	--bestn:	Top alignments to be reported by BLASR (default: 50)."
 	echo "			This parameter should be raised accordingly to the short reads coverage."
 	echo "			Its default value is adapted for a 50x coverage of short reads."
@@ -45,10 +45,11 @@ SR=""
 K=100
 seedsoverlap=0
 k=0
-solid=2
+solid=1
 branches=1500
 seedskips=5
-bestn=30
+mismatches=3
+bestn=50
 kmcmem="12"
 nproc=$(nproc)
 tmpdir=""
@@ -113,6 +114,11 @@ while [[ "$1" != "" ]] ; do
 			case "$2" in
 				"") echo "Error: $1 expects an argument" ; exit 1 ;;
 				*) seedskips="$2" ; shift 2 ;;
+			esac ;;
+		"--mismatches")
+			case "$2" in
+				"") echo "Error: $1 expects an argument" ; exit 1 ;;
+				*) mismatches="$2" ; shift 2 ;;
 			esac ;;
 		"--bestn")
 			case "$2" in
@@ -218,16 +224,8 @@ $hgf/bin/PgSAgen $tmpdir/"$K-mers.fa" $tmpdir/"$K-mers.fa" >> HG-CoLoR.stdout 2>
 
 echo "["$(date)"] Aligning the short reads on the long reads"
 $hgf/bin/formatLongReads.py "$longreads" > $tmpdir/"$formatLR"
-#Split the long reads file into multiple fragments, to overcome BLASR's 4Gb limation
-gt splitfasta -force -targetsize 2000 $tmpdir/"$formatLR"
 echo "----- blasr -----" >> HG-CoLoR.stderr
-#Run blasr on each fragment
-for frag in $tmpdir/$formatLR.*
-do
-	$hgf/bin/blasr $tmpdir/good_long_corrected_SR.fa $frag --nproc "$nproc" -m 6 --minAlnLength "$K" --bestn "$bestn" > $tmpdir/"sam_"$(basename $frag) 2>> HG-CoLoR.stderr
-done
-cat $tmpdir/sam_* > $tmpdir/"$aln"
-rm $tmpdir/sam_*
+$hgf/bin/blasr $tmpdir/good_long_corrected_SR.fa $tmpdir/"$formatLR" --nproc "$nproc" -m 6 --minAlnLength "$K" --bestn "$bestn" > $tmpdir/"$aln" 2>> HG-CoLoR.stderr
 echo "["$(date)"] Removing short alignments"
 sort -T $tmpdir/ -k 3 $tmpdir/"$aln" > $tmpdir/"tmp_$aln"
 mv $tmpdir/"tmp_$aln" $tmpdir/"$aln"
