Fix security issue with tmpdir and update general script

diff --git a/HG-CoLoR b/HG-CoLoR
--- a/HG-CoLoR
+++ b/HG-CoLoR
@@ -1,40 +1,40 @@
 #!/bin/bash
+set -e
 
 #Prints a help message
 function print_help {
-	echo "Usage: $0 [options] --longreads LR.fasta --shortreads SR.fastq --out result.fasta --tmpdir tmp_directory"
+	echo "Usage: $0 [options] --longreads LR.fasta --shortreads SR.fastq --out resultPrefix -K maxK"
 	echo ""
 	echo "Note: HG-CoLoR default parameters are adapted for a 50x coverage set of short reads with a 1% error rate."
-	echo "Please modify the parameters, in particular the --solid and --bestn ones, as indicated below if using a set of short reads with a much higher coverage and/or a highly different error rate."
+	echo "Please modify the parameters, in particular the --solid and --bestn ones, as indicated below"
+	echo "if using a set of short reads with a much higher coverage and/or a highly different error rate."
 	echo ""
 	echo "	Input:"
-	echo "	LR.fasta:	fasta file of long reads, one sequence per line."
-	echo "	SR.fastq:	fastq file of short reads."
-	echo "			Warning: only one file must be provided."
-	echo "			If using paired reads, please concatenate them into one single file."
-	echo "			It is recommended to run HG-CoLoR with a 50x coverage of short reads."
-	echo "			Results quality tends to drop with a higher coverage."
-	echo "	result.fasta:	fasta file where to output the corrected long reads."
-	echo "	tmp_directoty:	directory where to store the temporary files."
+	echo "	LR.fasta:                   fasta file of long reads, one sequence per line."
+	echo "	SR.fastq:                   fastq file of short reads."
+	echo "	                            Warning: only one file must be provided."
+	echo "	                            If using paired reads, please concatenate them into one single file."
+	echo "	resultPrefix:               Prefix of the fasta files where to output the corrected, trim and split long reads."
+	echo "	maxK:                       Maximum K-mer size of the variable-order de Bruijn Graph."
 	echo ""
 	echo "	Options:"
-	echo "	--maxorder:	Maximum order of the variable-order de Buijn graph (default: 100)."
-	echo "	--solid:	Minimum number of occurrences to consider a k-mer as solid, after short reads correction (default: 1)."
-	echo "			This parameter should be carefully raised accordingly to the short reads coverage and accuracy,"
-	echo "			and to the chosen maximum order of the graph."
-	echo "	--seedsoverlap:	Minimum overlap length to allow the merging of two overlapping seeds (default: maxorder - 1)."
-	echo "	--minorder:	Minimum order of the variable-order de Bruijn graph (default: maxorder / 2)."
-	echo "	--branches:	Maximum number of branches exploration (default: 1,500)."
-	echo "			Raising this parameter will result in less split corrected long reads."
-	echo "			However, it will also increase the runtime, and may create chimeric linkings between the seeds."
-	echo "	--seedskips:	Maximum number of seed skips (default: 5)."
-	echo "	--mismatches:	Allowed mismatches when attempting to link two seeds together (default: 3)."
-	echo "	--bestn:	Top alignments to be reported by BLASR (default: 50)."
-	echo "			This parameter should be raised accordingly to the short reads coverage."
-	echo "			Its default value is adapted for a 50x coverage of short reads."
-	echo "	--kmcmem: 	Maximum amount of RAM for KMC, in GB (default: 12)."
-	echo "	--nproc:	Number of processes to run in parallel (default: number of cores)."
-	echo "	--help:		Print this help message."
+	echo "	--minorder INT, -k INT:     Minimum k-mer size of the variable-order de Bruijn graph (default: K/2)."
+	echo "	--solid INT, -S INT:        Minimum number of occurrences to consider a short read k-mer as solid, after correction (default: 1)."
+	echo "	                            This parameter should be carefully raised accordingly to the short reads coverage and accuracy,"
+	echo "	                            and to the chosen maximum order of the graph."
+	echo "	--seedsoverlap INT, -o INT: Minimum overlap length to allow the merging of two overlapping seeds (default: K - 1)."
+	echo "	--branches INT, -b INT:     Maximum number of branches exploration (default: 1,250)."
+	echo "	                            Raising this parameter will result in less split corrected long reads."
+	echo "	                            However, it will also increase the runtime, and may create chimeric linkings between the seeds."
+	echo "	--seedskips INT, -s INT:    Maximum number of seed skips (default: 3)."
+	echo "	--mismatches INT, -m INT:   Allowed mismatches when attempting to link two seeds together (default: 3)."
+	echo "	--bestn INT, -n INT:        Top alignments to be reported by BLASR (default: 50)."
+	echo "	                            This parameter should be raised accordingly to the short reads coverage."
+	echo "	                            Its default value is adapted for a 50x coverage of short reads."
+	echo "	--nproc INT, -j INT:        Number of processes to run in parallel (default: number of cores)."
+	echo "	--tmpdir STRING, -t STRING: Path where to store the directory containing temporary files (default: working directory)."
+	echo "	--kmcmem INT, -r INT:       Maximum amount of RAM for KMC, in GB (default: 12)."
+	echo "	--help, -h:                 Print this help message."
 	exit 1
 }
 
@@ -43,17 +43,17 @@ longreads=""
 LR=""
 shortreads=""
 SR=""
-K=100
+K=0
 seedsoverlap=0
 k=0
 solid=1
-branches=1500
-seedskips=5
+branches=1250
+seedskips=3
 mismatches=3
 bestn=50
 kmcmem="12"
 nproc=$(nproc)
-tmpdir=""
+tmpdir="."
 out=""
 
 #Print help if no argument specified
@@ -64,7 +64,7 @@ fi
 #Otions handling
 while [[ "$1" != "" ]] ; do
 	case "$1" in
-		"--help")
+		"--help"|"-h")
 			print_help ;;
 		"--longreads")
 			case "$2" in
@@ -81,57 +81,57 @@ while [[ "$1" != "" ]] ; do
 				"") echo "Error: $1 expects an argument" ; exit 1 ;;
 				*) out="$2" ; shift 2 ;;
 			esac ;;
-		"--tmpdir")
-			case "$2" in
-				"") echo "Error: $1 expects an argument" ; exit 1 ;;
-				*) tmpdir="$2" ; shift 2 ;;
-			esac ;;
-		"--maxorder")
+		"--maxorder"|"-K")
 			case "$2" in
 				"") echo "Error: $1 expects an argument" ; exit 1 ;;
 				*) K="$2" ; shift 2 ;;
 			esac ;;
-		"--solid")
-			case "$2" in
-				"") echo "Error: $1 expects an argument" ; exit 1 ;;
-				*) solid="$2" ; shift 2 ;;
-			esac ;;
-		"--seedsoverlap")
-			case "$2" in
-				"") echo "Error: $1 expects an argument" ; exit 1 ;;
-				*) seedsoverlap="$2" ; shift 2 ;;
-			esac ;;
-		"--minorder")
+		"--minorder"|"-k")
 			case "$2" in
 				"") echo "Error: $1 expects an argument" ; exit 1 ;;
 				*) k="$2" ; shift 2 ;;
 			esac ;;
-		"--branches")
+		"--solid"|"-S")
+			case "$2" in
+				"") echo "Error: $1 expects an argument" ; exit 1 ;;
+				*) solid="$2" ; shift 2 ;;
+			esac ;;
+		"--seedsoverlap"|"-o")
+			case "$2" in
+				"") echo "Error: $1 expects an argument" ; exit 1 ;;
+				*) seedsoverlap="$2" ; shift 2 ;;
+			esac ;;
+		"--branches"|"-b")
 			case "$2" in
 				"") echo "Error: $1 expects an argument" ; exit 1 ;;
 				*) branches="$2" ; shift 2 ;;
 			esac ;;
-		"--seedskips")
+		"--seedskips"|"-s")
 			case "$2" in
 				"") echo "Error: $1 expects an argument" ; exit 1 ;;
 				*) seedskips="$2" ; shift 2 ;;
 			esac ;;
-		"--mismatches")
+		"--mismatches"|"-m")
 			case "$2" in
 				"") echo "Error: $1 expects an argument" ; exit 1 ;;
 				*) mismatches="$2" ; shift 2 ;;
 			esac ;;
-		"--bestn")
+		"--bestn"|"-n")
 			case "$2" in
 				"") echo "Error: $1 expects an argument" ; exit 1 ;;
 				*) bestn="$2" ; shift 2 ;;
 			esac ;;
-		"--nproc")
+		"--nproc"|"-j")
 			case "$2" in
 				"") echo "Error: $1 expects an argument" ; exit 1 ;;
 				*) nproc="$2" ; shift 2 ;;
 			esac ;;
-		"--kmcmem")
+		"--tmpdir"|"-t")
+			case "$2" in
+				"") echo "Error: $1 expects an argument" ; exit 1 ;;
+				*) tmpdir="$2" ; shift 2 ;;
+			esac ;;
+		"--kmcmem"|"-r")
 			case "$2" in
 				"") echo "Error: $1 expects an argument" ; exit 1 ;;
 				*) jfhash="$2" ; shift 2 ;;
@@ -142,14 +142,6 @@ while [[ "$1" != "" ]] ; do
 			echo "Error: invalid option \"$1\"" ; exit 1 ;;
   	esac
 done
-
-#If seedsoverlap or minorder haven't been set, set them to default values
-if [[ $seedsoverlap -eq 0 ]] ; then
-	seedsoverlap=$((K-1))
-fi
-if  [[ $k -eq 0 ]] ; then
-	k=$((K/2))
-fi
 
 #Exit if no short reads, no long reads, no temporary directory, or no output files have been specified
 if [[ $LR == "" ]] ; then
@@ -164,9 +156,17 @@ if [[ $out == "" ]] ; then
 	echo "Error: --out must be specified";
 	exit 1;
 fi
-if [[ $tmpdir = "" ]] ; then
-	echo "Error: --tmpdir must be specified";
+if [[ $K -eq 0 ]] ; then
+	echo "Error: -K must be specified";
 	exit 1;
+fi
+
+#If seedsoverlap or minorder haven't been set, set them to default values
+if [[ $seedsoverlap -eq 0 ]] ; then
+	seedsoverlap=$((K-1))
+fi
+if  [[ $k -eq 0 ]] ; then
+	k=$((K/2))
 fi
 
 #Remove the output file if it already exists
@@ -174,14 +174,20 @@ if [[ -f $out ]] ; then
 	rm $out
 fi
 
-#Create the directory for temporary files, if it does not exist
-if [[ ! -d $tmpdir ]] ; then
-        mkdir $tmpdir
+#Create the directory for temporary files
+if [[ -d $tmpdir ]] ; then
+	tmpdir="$tmpdir/HGC_"$$
+        mkdir -p $tmpdir
 fi
 
 #Create the subdirectory for alignments files, if it does not exist
 if [[ ! -d $tmpdir/Alignments ]] ; then
 	mkdir $tmpdir/Alignments
+fi
+
+#Create the subdirectory for raw long reads, if it does not exist
+if [[ ! -d $tmpdir/RawLongReads ]] ; then
+	mkdir $tmpdir/RawLongReads
 fi
 
 #Temporary files names
@@ -223,11 +229,14 @@ echo "----- PgSAgen -----" >> HG-CoLoR.stdout
 echo "----- PgSAgen -----" >> HG-CoLoR.stderr
 $hgf/bin/PgSAgen $tmpdir/"$K-mers.fa" $tmpdir/"$K-mers.fa" >> HG-CoLoR.stdout 2>> HG-CoLoR.stderr
 
-echo "["$(date)"] Aligning the short reads on the long reads"
+echo "["$(date)"] Preparing the raw long reads temporary files"
 $hgf/bin/formatLongReads.py "$longreads" > $tmpdir/"$formatLR"
+$hgf/bin/prepareRawLongReads.py $tmpdir/"$formatLR" $tmpdir/RawLongReads/
+
+echo "["$(date)"] Aligning the short reads on the long reads"
 echo "----- blasr -----" >> HG-CoLoR.stderr
 $hgf/bin/blasr $tmpdir/good_long_corrected_SR.fa $tmpdir/"$formatLR" --nproc "$nproc" -m 6 --minAlnLength "$K" --bestn "$bestn" > $tmpdir/"$aln" 2>> HG-CoLoR.stderr
-echo "["$(date)"] Removing short alignments"
+echo "["$(date)"] Preparing the alignments temporary files"
 sort -T $tmpdir/ -k 3 $tmpdir/"$aln" > $tmpdir/"tmp_$aln"
 mv $tmpdir/"tmp_$aln" $tmpdir/"$aln"
 $hgf/bin/filterOutShortAlignments.py $tmpdir/"$aln" "$K" $tmpdir/Alignments/
@@ -235,9 +244,11 @@ rm $tmpdir/"$aln"
 ls $tmpdir/Alignments/ > $tmpdir/"$seeds"
 
 echo "["$(date)"] Generating the corrected long reads"
-$hgf/bin/CLRgen -t "$tmpdir" -K "$K" -o "$seedsoverlap" -k "$k" -b "$branches" -s "$seedskips" -j "$nproc" $tmpdir/"$K-mers.fa.pgsa" > "$out"
+$hgf/bin/CLRgen -t "$tmpdir" -K "$K" -o "$seedsoverlap" -k "$k" -b "$branches" -s "$seedskips" -j "$nproc" $tmpdir/"$K-mers.fa.pgsa" > "$out.fasta"
+$hgf/bin/trim.py "$out.fasta" > "$out.trim.fasta"
+$hgf/bin/split.py "$out.trim.fasta" > "$out.split.fasta"
 
-echo "["$(date)"] Removing temporary files"
+echo "["$(date)"] Removing the temporary files"
 rm -Rf $tmpdir
 
 echo "["$(date)"] Exiting"
