Code optimization

diff --git a/HG-CoLoR b/HG-CoLoR
--- a/HG-CoLoR
+++ b/HG-CoLoR
@@ -2,14 +2,15 @@
 
 #Prints a help message
 function print_help {
-	echo "Usage: $0 [options] --longreads LR.fasta --shortreads SR.fastq --out result.fasta"
+	echo "Usage: $0 [options] --longreads LR.fasta --shortreads SR.fastq --out result.fasta --tmpdir tmp_directory"
 	echo ""
-	echo "	Input files:"
+	echo "	Input:"
 	echo "	LR.fasta:	fasta file of long reads, one sequence per line."
 	echo "	SR.fastq:	fastq file of short reads."
 	echo "			Warning: only one file must be provided."
 	echo "			If using paired reads, please concatenate them into one single file."
 	echo "	result.fasta:	fasta file where to output the synthetic long reads."
+	echo "	tmp_directoty:	file where to store the temporary files."
 	echo ""
 	echo "	Options:"
 	echo "	--kmer:		k-mer size for the graph construction (default: 64)."
@@ -36,6 +37,7 @@ backtracks=1125
 seedskips=5
 bestn=10
 nproc=$(nproc)
+tmpdir=""
 out=""
 
 #Print help if no argument specified
@@ -62,6 +64,11 @@ while [[ "$1" != "" ]] ; do
 			case "$2" in
 				"") echo "Error: $1 expects an argument" ; exit 1 ;;
 				*) out="$2" ; shift 2 ;;
+			esac ;;
+		"--tmpdir")
+			case "$2" in
+				"") echo "Error: $1 expects an argument" ; exit 1 ;;
+				*) tmpdir="$2" ; shift 2 ;;
 			esac ;;
 		"--kmer")
 			case "$2" in
@@ -126,6 +133,10 @@ if [[ $out == "" ]] ; then
 	echo "Error: --out must be specified";
 	exit 1;
 fi
+if [[ $tmpdir = "" ]] ; then
+	echo "Error: --tmpdir must be specified";
+	exit 1;
+fi
 
 #Remove the output file if it already exists
 if [[ -f $out ]] ; then
@@ -146,29 +157,29 @@ echo "...Done"
 rm quorum_corrected.log
 rm quorum_corrected_mer_database.jf
 echo "Extracting the short reads' k-mers and building the index..."
-./bin/filterShortReads.py quorum_corrected.fa "$k" > long_quorum_corrected.fa
+./bin/filterShortReads.py quorum_corrected.fa "$k" > $tmpdir/long_quorum_corrected.fa
 rm quorum_corrected.fa
-revseq long_quorum_corrected.fa -reverse -complement -outseq RC_long_quorum_corrected.fa 2>> "$errlog"
-cat long_quorum_corrected.fa RC_long_quorum_corrected.fa > all_long_quorum_corrected.fa
-jellyfish count -m "$k" -s 500M -t "$nproc" all_long_quorum_corrected.fa
-rm RC_long_quorum_corrected.fa
-rm all_long_quorum_corrected.fa
-jellyfish dump mer_counts.jf > "$k-mers-$SR"
-rm mer_counts.jf
-sed -i '/>.*/d' "$k-mers-$SR"
-./PgSAgen "$k-mers-$SR" "$k-mers-$SR" >> "$log" 2>> "$errlog"
+revseq $tmpdir/long_quorum_corrected.fa -reverse -complement -outseq $tmpdir/RC_long_quorum_corrected.fa 2>> /dev/null
+cat $tmpdir/long_quorum_corrected.fa $tmpdir/RC_long_quorum_corrected.fa > $tmpdir/all_long_quorum_corrected.fa
+jellyfish count -m "$k" -s 500M -t "$nproc" $tmpdir/all_long_quorum_corrected.fa
+rm $tmpdir/RC_long_quorum_corrected.fa
+rm $tmpdir/all_long_quorum_corrected.fa
+jellyfish dump $tmpdir/mer_counts.jf > $tmpdir/"$k-mers-$SR"
+rm $tmpdir/mer_counts.jf
+sed -i '/>.*/d' $tmpdir/"$k-mers-$SR"
+./PgSAgen $tmpdir/"$k-mers-$SR" $tmpdir/"$k-mers-$SR" >> /dev/null 2>> /dev/null
 echo "...Done"
 
 echo "Aligning the short reads on the long reads..."
-./bin/formatLongReads.py "$longreads" > "$formatLR"
-./bin/blasr long_quorum_corrected.fa "$formatLR" --nproc "$nproc" -m 6 --minAlnLength "$k" --bestn "$bestn" > "$aln" 2>> "$errlog"
-rm long_quorum_corrected.fa
-./bin/filterOutShortAlignments.py "$aln" "$k" > "tmp_$aln"
-mv "tmp_$aln" "$aln"
+./bin/formatLongReads.py "$longreads" > $tmpdir/"$formatLR"
+./bin/blasr long_quorum_corrected.fa $tmpdir/"$formatLR" --nproc "$nproc" -m 6 --minAlnLength "$k" --bestn "$bestn" > $tmpdir/"$aln" 2>> /dev/null
+rm $tmpdir/long_quorum_corrected.fa
+./bin/filterOutShortAlignments.py $tmpdir/"$aln" "$k" $tmpdir
+mv $tmpdir/"tmp_$aln" $tmpdir/"$aln"
 echo "...Done"
 echo "Generating the sythetic long reads..."
 echo "$minoverlap"
-cut -f 3 "$aln" | sort -u > "$seeds"
-parallel -j "$nproc" ./generateSLR "$aln" "$k" "$k-mers-$SR.pgsa" "$seedsoverlap" "$minoverlap" "$backtracks" "$seedskips" "$out" :::: $seeds
+cut -f 3 $tmpdir/"$aln" | sort -u > $tmpdir/"$seeds"
+parallel -j "$nproc" ./generateSLR $tmpdir/"$aln" "$k" $tmpdir/"$k-mers-$SR.pgsa" "$seedsoverlap" "$minoverlap" "$backtracks" "$seedskips" "$out" :::: $tmpdir/$seeds
 echo "..Done"
-rm $log $errlog $aln $formatLR "$k-mers-$SR" "$k-mers-$SR.pgsa" $seeds
+rm $tmpdir/$aln $tmpdir/$formatLR $tmpdir/"$k-mers-$SR" $tmpdir/"$k-mers-$SR.pgsa" $tmpdir/$seeds
